version: 2.1

jobs:
  build-and-push-docker:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: latest
      - run:
          name: Log in to Docker Hub
          command: |-
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run:
          name: Build Docker Image
          command: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${CIRCLE_SHA1} .
      - run:
          name: Push Docker Image
          command: |-
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${CIRCLE_SHA1}
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${CIRCLE_SHA1} ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

workflows:
  build-and-test-and-deploy:
    jobs:
      - test-java
      - build-and-push-docker:
          requires:
            - test-java
