version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: ${{ secret.DOCKERHUB_USERNAME }}
          password: ${{ secret.DOCKERHUB_TOKEN }}
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t ${{ secret.DOCKERHUB_USERNAME }}/testapi:$TAG .
      - run:
          name: Push application Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo ${{ secret.DOCKERHUB_TOKEN }} | docker login -u ${{ secret.DOCKERHUB_USERNAME }} --password-stdin
            docker push ${{ secret.DOCKERHUB_USERNAME }}/testapi:$TAG
